// <auto-generated />
using System;
using FabelioScrape.Web.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FabelioScrape.Web.Migrations
{
    [DbContext(typeof(MetaDataDbContext))]
    [Migration("20200130023410_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("FabelioScrape.Web.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(512);

                    b.Property<int>("FinalPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrls_Json")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<DateTimeOffset>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastSyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PageUrl")
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
